### PR TITLE
chore: Remove the date from the blog URL

### LINKED ISSUE #275: Remove the date from the blog URL
## Current

image

The blog URL contains the date. Some articles will be updated for a long time, so including the date is not appropriate.

## Expectation

Change it to the following format.

image

Old URLs need to be redirected.

### PR DESCRIPTION
**Pull request by sy-records**
Fix #275

How should we name the post file?

1. As before, the `slug` needs to be added. Example: `2024-11-27-apache-answer-1.4.1-release`, Add `slug`
2. Move out the year, month and day, the default is `slug`. Example: `apache-answer-1.4.1-release`

### CODE REVIEW

**Comment by fenbox** [comment]
Long pain is not as good as short pain, I choose choice 2.

**Comment by sy-records** [comment]
Done. It can be accessed at https://change-url.apache-answer.pages.dev/.

**Comment by shuashuai** [comment]
> Done. It can be accessed at https://change-url.apache-answer.pages.dev/.

Functionality is fine, the `docusaurus.config.js` configuration file could be optimized by extracting the url for redirect into a separate file so that it doesn't affect the reading of `docusaurus.config.js`.

eg: 

create `redirect.js` file
```
module.exports = [ 
  {
    to: '/community/support',
    from: ['/contact', '/community'],
  },
  ...
]
```
require and use in docusaurus.config.js file

eg: 
```
const redirectPaths = require('./redirect.js');

[
      '@docusaurus/plugin-client-redirects',
      {
        redirects: redirectPaths,
      },
    ],

```

**Review by shuashuai — APPROVED** [review]
Thanks!

**Pull request merged**
